
== Checklist for water meter examinations and performance tests

=== Checklist for water meter examinations

[%unnumbered,cols="15a,45a,3a,3a,34a",options="header"]
|===
| OIML R 49-1:2024, subclause | Requirement | {plus} | − | Remarks

5+| *Function of the indicating device*

| 6.7.1.1
| The indicating device shall provide an easily read, reliable and unambiguous
visual indication of the indicated volume.
| | |

| 6.7.1.1
| The indicating device shall include visual means for testing and calibration.
| | |

| 6.7.1.1
| The indicating device may include additional elements for testing and calibration
by other methods, e.g. for automatic testing and calibration.
| | |

5+| *Unit of measurement and its placement*

| 6.7.1.2
| The indicated volume of water shall be expressed in cubic metres
| | |

| 6.7.1.2
| The symbol stem:["unitsml(m^3)"] shall appear on the dial or immediately adjacent
to the numbered display
| | |

5+| *Indicating range*

| 6.7.1.3
| For stem:[Q_3 <= 6.3], the minimum indicating range is stem:[0 "unitsml(m^3)"]
to stem:[9999 "unitsml(m^3)"]
| | |

| 6.7.1.3
| For stem:[6.3 < Q_3 <= 63], the minimum indicating range is stem:[0 "unitsml(m^3)"]
to stem:[99999 "unitsml(m^3)"]
| | |

| 6.7.1.3
| For stem:[63 < Q_3 <= 630], the minimum indicating range is stem:[0 "unitsml(m^3)"]
to stem:[999999 "unitsml(m^3)"]
| | |

| 6.7.1.3
| For stem:[630 < Q_3 <= 6300], the minimum indicating range is stem:[0 "unitsml(m^3)"]
to stem:[9999999 "unitsml(m^3)"]. See footnote
4.footnote:[may be expanded to larger values of stem:[Q_3]]
| | |

5+| *Colour coding for indicating device*

| 6.7.1.4
| The colour black should be used to indicate the cubic metre and its multiples.
| | |
|===

<<<

[%unnumbered,cols="15a,45a,3a,3a,34a",options="header"]
|===
| OIML R 49-1:2024, subclause | Requirement | {plus} | − | Remarks

| 6.7.1.4
| The colour red should be used to indicate sub-multiples of a cubic metre.
| | |

| 6.7.1.4
| The colours shall be applied to either the pointers, indexes, numbers, wheels,
discs, dials or aperture frames.
| | |

| 6.7.1.4
| Other means of indicating the cubic metre may be used provided there is no
ambiguity in distinguishing between the primary indication and alternative displays,
e.g. sub-multiples for verification and testing.
| | |

5+| *Types of indicating device: Type 1 -- Analogue device*

| 6.7.2.1
| The indicated volume shall be shown by continuous movement of either:

. one or more pointers moving relative to graduated scales; or

. one or more circular scales or drums each passing an index.
| | |

| 6.7.2.1
| The value expressed in cubic metres for each scale division shall be of the
form stem:[10^n], where stem:[n] is a positive or a negative whole number or
zero, thereby establishing a system of consecutive decades.
| | |

| 6.7.2.1
| The scale shall be graduated in values expressed in cubic metres or accompanied
by a multiplying factor

(stem:[xx 0.001]; stem:[xx 0.01]; stem:[xx 0.1]; stem:[xx 1]; stem:[xx 10];
stem:[xx 100]; stem:[xx 1000], etc.)
| | |

| 6.7.2.1
| Rotational movement of the pointers or circular scales shall be clockwise.
| | |

| 6.7.2.1
| Linear movement of pointers or scales shall be left to right.
| | |

| 6.7.2.1
| Movement of numbered roller indicators (drums) shall be upwards.
| | |

5+| *Types of indicating device: Type 2 -- Digital device*

| 6.7.2.2
| The indicated volume is given by a line of digits appearing in one or more
apertures.
| | |
|===

<<<

[%unnumbered,cols="15a,45a,3a,3a,34a",options="header"]
|===
| OIML R 49-1:2024, subclause
| Requirement
| {plus}
| −
| Remarks

| 6.7.2.2
| The advance of one digit shall be completed while the digit of the next immediately
lower decade changes from 9 to 0.
| | |

| 6.7.2.2
| The apparent height of the digits shall be at least stem:[4 "unitsml(mm)"].
| | |

| 6.7.2.2
| For non-electronic devices, movement of numbered roller indicators (drums)
shall be upwards.
| | |

| 6.7.2.2
| For non-electronic devices, the lowest value decade may have a continuous
movement, the aperture being large enough to permit a digit to be read without
ambiguity.
| | |

| 6.7.2.2
| For electronic devices with non-permanent displays the volume shall be able
to be displayed at any time for at least stem:[10 "unitsml(s)"].
| | |

| 6.7.2.2
| For electronic devices, the meter shall provide visual checking of the entire
display which shall have the following sequence:

* for seven segment type displaying all the elements (e.g. an "eights" test); and

* for seven segment type blanking all the elements (a "blanks" test).

For graphical displays, an equivalent test is required to demonstrate that display
faults cannot result in any digit being misinterpreted.

Each step of the sequence shall last at least stem:[1 "unitsml(s)"].
| | |

5+| *Types of indicating device: Type 3 -- Combination of analogue and digital
devices*

| 6.7.2.3
| The indicated volume is given by a combination of type 1 and type 2 devices
and the respective requirements of each shall apply.
| | |

5+| *Verification devices -- General requirements*

| 6.7.3.1
| Every indicating device shall provide means for visual, non-ambiguous verification
testing and calibration.
| | |

| 6.7.3.1
| The visual verification may have either a continuous or a discontinuous movement.
| | |
|===

<<<

[%unnumbered,cols="15a,45a,3a,3a,34a",options="header"]
|===
| OIML R 49-1:2024, subclause | Requirement | {plus} | − | Remarks

| 6.7.3.1
| In addition to the visual verification display, an indicating device may include
provisions for rapid testing by the inclusion of complementary elements (e.g.
star wheels or discs), providing signals through externally attached sensors.
Such a provision may also be used for leak detection.
| | |

5+| *Verification devices -- Visual verification displays*

| 6.7.3.2.1
| The value of the verification scale interval, expressed in cubic metres, shall
be of the form: stem:[1 xx 10^n], stem:[2 xx 10^n] or stem:[5 xx 10^n], where
stem:[n] is a positive or negative whole number, or zero.
| | |

| 6.7.3.2.1
| For analogue or digital indicating devices with continuous movement of the
first element, the verification scale interval may be formed from the division
into 2, 5 or 10 equal parts of the interval between two consecutive digits of
the first element. Numbering shall not be applied to these divisions.
| | |

| 6.7.3.2.1
| For digital indicating devices with discontinuous movement of the first element,
the verification scale interval is the interval between two consecutive digits
or incremental movements of the first element.
| | |

| 6.7.3.2.2
| On indicating devices with continuous movement of the first element, the apparent
scale spacing shall be not less than stem:[1 "unitsml(mm)"] and not more than
stem:[5 "unitsml(mm)"].
| | |

| 6.7.3.2.2
| The scale shall consist of either:

. lines of equal thickness not exceeding one quarter of the scale spacing and
differing only in length; or

. contrasting bands of a constant width equal to the scale spacing.
| | |

| 6.7.3.2.2
| The apparent width of the pointer at its tip shall not exceed one-quarter
of the scale spacing and in no case shall it be greater than stem:[0.5 "unitsml(mm)"].
| | |

5+| *Resolution of the indicating device*

| 6.7.3.2.3
| Additional verification elements may be used provided that the uncertainty
of reading is not greater than stem:[0.25 %] of the test volume for accuracy
class 1 meters and stem:[0.5 %] of the test volume for accuracy
| | |
|===

<<<

[%unnumbered,cols="15a,45a,3a,3a,34a",options="header"]
|===
| OIML R 49-1:2024, subclause | Requirement | {plus} | − | Remarks

| | class 2 meters and that the correct functioning of the register is checked.
| | |

| 6.7.3.2.3
| When the display of the first element is continuous, an allowance shall be
made for a maximum error in each reading of not more than half the verification
scale interval.
| | |

| 6.7.3.2.3
| When the display of the first element is discontinuous, an allowance shall
be made for a maximum error in each reading of not more than one digit of the
verification scale.
| | |

| 6.7.3.3
| 6.7.3.3 Combination meters

For combination meters with two indicating devices, 6.7.3.1 and 6.7.3.2 apply
to both indicating devices.
| | |

5+| *Marks and inscriptions*

| 6.6.1
| A place shall be provided on the meter for affixing the verification mark,
which shall be visible without dismantling the meter.
| | |

| 6.6.2
| The water meter shall be clearly and indelibly marked with the information
listed in the following, either grouped or distributed on the casing, the indicating
device dial, an identification plate or on the meter cover if is not detachable.
These markings shall be visible without dismantling the water meter after the
instrument has been placed on the market or put into use.
| | |

5+|
NOTE: In the case of a combination meter, the markings in the following
refer to the combination meter considered as a single meter.

| 6.6.2 a)
| Unit of measurement: cubic metre.
| | |

| 6.6.2 b)
| The accuracy class, where it differs from accuracy class 2.
| | |

| 6.6.2 c)
| Numerical value of stem:[Q_3] and the ratio stem:[Q_3//Q_1]: if the meter
measures reverse flow and the values of stem:[Q_3] and the ratio stem:[Q_3//Q_1]
are different in the two directions, both values of stem:[Q_3] and stem:[Q_3//Q_1]
shall be inscribed; the direction of flow to which each pair of values refers
shall be clear. The ratio stem:[Q_3//Q_1] may be expressed as R, e.g. "R160".
If the meter has different values of stem:[Q_3//Q_1] in horizontal and vertical
| | |
|===

<<<

[%unnumbered,cols="15a,45a,3a,3a,34a",options="header"]
|===
| OIML R 49-1:2024, subclause | Requirement | {plus} | − | Remarks

|
| positions, both values of stem:[Q_3//Q_1] shall be inscribed, and the orientation
to which each value refers shall be clear.
| | |

| 6.6.2 d)
| The type approval sign according to national regulations.
| | |

| 6.6.2 e)
| The name or trademark of the manufacturer.
| | |

| 6.6.2 f)
| The year of manufacture, the last two digits of the year of manufacture or
the month and year of manufacture.
| | |

| 6.6.2 g)
| The serial number (as near as possible to the indicating device).
| | |

| 6.6.2 h)
| The direction of flow by means of an arrow (shown on both sides of the body;
or on one side only, provided the direction of flow arrow is easily visible
under all circumstances).
| | |

| 6.6.2 i)
| The maximum admissible pressure (MAP) if it exceeds stem:[1 "unitsml(MPa)"]
(stem:[10 "unitsml(bar)"]) or stem:[0.6 "unitsml(MPa)"] (stem:[6 "unitsml(bar)"])
for nominal diameter stem:[>= 500 "unitsml(mm)"].
| | |

| 6.6.2 j)
| The letter V and/or H, if the meter can only be operated in the vertical position
and/or horizontal position with the indicating device positioned on top.
| | |

| 6.6.2 k)
| The temperature class as specified in Table 1 where it differs from T30.
| | |

| 6.6.2 l)
| The pressure loss class where it differs from Δp 63.
| | |

| 6.6.2 m)
| The installation sensitivity class where it differs from U0/D0.
| | |

5+| *Additional markings for water meters with electronic devices*

| 6.6.2 n)
| For an external power supply: the voltage and frequency.
| | |

| 6.6.2 o)
| For a replaceable battery: the latest date by which the battery shall be replaced.
| | |

| 6.6.2 p)
| For a non-replaceable battery: the latest date by which the meter shall be
replaced.
| | |
|===

<<<

[%unnumbered,cols="15a,45a,3a,3a,34a",options="header"]
|===
| OIML R 49-1:2024, subclause | Requirement | {plus} | − | Remarks

| 6.6.2 q)
| Environmental classification.
| | |

| 6.6.2 r)
| Electromagnetic environmental class.
| | |

| 6.6.2
| The environmental classification and electromagnetic environmental class may
be given on a separate datasheet, unambiguously related to the meter by a unique
identification, and not on the meter itself.
| | |

5+| *Protection devices*

| 6.8.1
| Water meters shall include protection devices which can be sealed so as to
prevent, both before and after correct installation of the water meter, dismantling
or modification of the meter, its adjustment device or its correction device,
without damaging these devices. In the case of combination meters, this requirement
applies to both meters.
| | |

| 6.8.1
| The display of the total quantity supplied or the displays from which the
total quantity supplied can be derived shall not be resettable while the meter
is in service to a single customer.
| | |

5+| *Protection devices -- Electronic sealing devices*

| 6.8.2.1
| When access to parameters that influence the determination of the results
of measurements is not protected by mechanical sealing devices, the protection
shall fulfil the following provisions:

. Access shall only be allowed to authorised people, e.g. by means of a code
(password) or of a special device (hard key, etc.). The code shall be capable
of being changed.

. It shall be possible for evidence of an intervention to be available for a
period of time as defined in national regulations. The record shall include
the date and a characteristic element identifying the authorised person making
the intervention [see a)]. If deletion of a previous intervention is necessary
to permit a new record, the oldest record shall be deleted.
| | |

| 6.8.2.2
| For meters with parts which can be disconnected one from another by the user
and which are
| | |
|===

<<<

[%unnumbered,cols="15a,45a,3a,3a,34a",options="header"]
|===
| OIML R 49-1:2024, subclause | Requirement | {plus} | − | Remarks

|
| interchangeable, the following provisions shall be fulfilled:

. it shall not be possible to access parameters that participate in the determination
of results of measurements through disconnected points unless the provisions
of OIML R 49-1:2024, 6.8.2.1 are fulfilled;

. interposing any device which may influence the accuracy shall be prevented
by means of electronic and data processing securities or, if this is not possible,
by mechanical means.
| | |

| 6.8.2.3
| For meters with parts which may be disconnected one from the other by the
user and which are not interchangeable, the provisions in OIML R 49-1:2024,
6.8.2.2 apply.

Moreover, these meters shall be provided with devices or means which do not
allow them to operate if the various parts are not connected according to the
approved type.

They shall be provided with a device that prevents any measurement after any
unauthorised disconnection and subsequent reconnection by the user.
| | |

5+| *Examination and testing of checking facilities*

5+| *General requirements for examining checking facilities*

| 5.1.3
| Water meters with electronic devices shall be provided with the checking facilities
(OIML R 49-1, 3.5.4) specified in OIML R 49-1:2024, Annex B. The meter manufacturers
shall declare which checking facilities are provided with the meter.
| | |

| 5.1.3
| All water meters equipped with checking facilities shall prevent or detect
reverse flow, as laid down in OIML R 49-1:2024, 4.2.7.
| | |
|===

<<<

=== Performance tests for all water meters

[%unnumbered,cols="15a,45a,3a,3a,34a",options="header"]
|===
| OIML R 49-1:2024, subclause | Requirement | {plus} | − | Remarks

5+| *Static pressure test*

| 4.2.10
| The meter shall be capable of withstanding the following test pressures without
leakage or damage:

* 1.6 times the maximum admissible pressure for stem:[15 "unitsml(min)"];

* 2 times the maximum admissible pressure for stem:[1 "unitsml(min)"].
| | |

5+| *Intrinsic errors (of indication)*

| 7.2.3
| The errors (of indication) of the water meter (in the measurement of the
actual volume), shall be determined at least at the following flow rate ranges:

. stem:[Q_1] to stem:[1.1 Q_1];

. stem:[Q_2] to stem:[1.1 Q_2];

. stem:[0.33(Q_2 + Q_3)] to stem:[0.37(Q_2 + Q_3)];

. stem:[0.67(Q_2 + Q_3)] to stem:[0.74(Q_2 + Q_3)];

. stem:[0.9 Q_3] to stem:[Q_3];

. stem:[0.95 Q_4] to stem:[Q_4];

and for combination meters;

[start=7]
. stem:[0.85 Q_(x1)] to stem:[0.95 Q_(x1)];

. stem:[1.05 Q_(x2)] to stem:[1.15 Q_(x2)].

The water meter should be tested without its temporary supplementary devices
attached (if any).

During a test all other influence factors shall be held at reference conditions.

Other flow rates may be tested depending on the shape of the error curve.
| | |
|===

<<<

[%unnumbered,cols="15a,45a,3a,3a,34a",options="header"]
|===
| OIML R 49-1:2024, subclause | Requirement | {plus} | − | Remarks

| |
[arabic]
. The errors (of indication) observed for each of the above flow rates shall
not exceed the maximum permissible errors (MPEs) given in OIML R 49-1:2024,
4.2.2 or 4.2.3.

NOTE: See OIML R 49-2:2024, 7.4.4 for the permitted flow rate ranges and
OIML R 49-2:2024, 7.4.4 and 7.4.5 for the required number of measurements at
each flow rate.

Meters shall be tested in the orientations corresponding to their marking or
lack thereof.

NOTE: See OIML R 49-2, 7.4.2.2.7.5 for testing orientations.
| | |

| 7.2.4
| Repeatability

The meter shall be repeatable: the standard deviation of three measurements
at the same flow rate shall not exceed one-third of the MPEs given in OIML R
49-1:2024, 4.2.2 or 4.2.3. Tests shall be carried out at nominal flow rates
of stem:[Q_1], stem:[Q_2], and stem:[Q_3].
| | |

5+| *Water temperature test*

| 4.2.8
| The requirements relating to the MPEs shall be met for all water temperature
variations within the rated operating conditions of the meter.
| | |

5+| *Water pressure test*

| 4.2.8
| The requirements relating to the MPEs shall be met for all temperature and
pressure variations occurring within the rated operating conditions of the water
meter.
| | |

5+| *Reverse flow test*

| 4.2.7
| The manufacturer shall specify whether or not a water meter is designed to
measure reverse flow.
| | |

| 4.2.7
| A water meter designed to measure reverse flow shall either:

. subtract the reverse flow volume from the indicated volume; or
| | |
|===

<<<

[%unnumbered,cols="15a,45a,3a,3a,34a",options="header"]
|===
| OIML R 49-1:2024, subclause | Requirement | {plus} | − | Remarks

| |
[start=2]
. record the reverse flow volume separately.

The MPEs of OIML R 49-1:2024, 4.2.2 or 4.2.3 shall be met for both forward and
reverse flow.

For meters designed to measure reverse flow, the permanent flow rate and the
measuring range may be different in each direction.
| | |

| 4.2.7
| A water meter not designed to measure reverse flow shall either:

. prevent it; or

. be capable of withstanding an accidental reverse flow at a flow rate up to
stem:[Q_3] without any deterioration or change in its metrological properties
for forward flow.
| | |

5+| *Meter characteristics at zero flow rate*

| 4.2.9
| The water meter totalisation shall not change in the absence either of flow
or of water.
| | |

5+| *Pressure loss test*

| 6.5
| The pressure loss of the water meter, including its filter where the latter
forms an integral part of the water meter, shall not be greater than
stem:[0.063 "unitsml(MPa)"] (stem:[0.63 "unitsml(bar)"]) between stem:[Q_1]
and stem:[Q_3].
| | |

5+| *Flow disturbance test*

| 6.3.4
| If the accuracy of water meters is affected by disturbances in the upstream
or downstream pipeline (e.g. due to the presence of bends, valves or pumps),
the water meter shall be provided with a sufficient straight pipe lengths with
or without a flow straightener (as specified by the manufacturer) so that the
indications of the installed water meter do not exceed MPEs of OIML R 49-1,
4.2.2 or 4.2.3, according to the accuracy class of the meter.

Forward flow tests

Reverse flow tests (where applicable)
| | |
|===

<<<

[%unnumbered,cols="15a,45a,3a,3a,34a",options="header"]
|===
| OIML R 49-1:2024, subclause | Requirement | {plus} | − | Remarks

5+| *Overload temperature test*

| 7.2.5
| Water meters with stem:["MAT" >= 50 "unitsml(degC)"] shall be capable of withstanding
a water temperature of stem:["MAT" + 10 "unitsml(degC)"] for stem:[1 "unitsml(h)"].

The test is specified in OIML R 49-2, 7.6.
| | |

5+| *Durability tests*

| 7.2.6
| The water meter shall undergo a durability test according to the permanent
flow rate stem:[Q_3] and the overload flow rate stem:[Q_4] of the meter, simulating
service conditions.

The test is specified in OIML R 49-2, 7.11.
| | |

| 7.2.6
| Meters with stem:[Q_3 <= 16 "unitsml(m^3/h)"]:

. stem:[100000] flow cycles between stem:[0] and stem:[Q_3];

. stem:[100 "unitsml(h)"] at stem:[Q_4].
| | |

| 7.2.6
| Meters with stem:[Q_3 > 16 "unitsml(m^3/h)"]:

. stem:[800 "unitsml(h)"] at stem:[Q_3];

. stem:[200 "unitsml(h)"] at stem:[Q_4];

and for combination meters:

[start=3]
. stem:[50000] flow cycles between stem:[Q >= 2 Q_(x2)] and stem:[0].
| | |

| 7.2.6.2
| Accuracy class 1 meters

The variation in the error curve (of indication) shall not exceed stem:[2 %]
for flow rates in the lower zone (stem:[Q_1 <= Q < Q_2]) and stem:[1 %] for
flow rates in the upper zone (stem:[Q_2 <= Q <= Q_4]).

For flow rates in the lower flow rate zone (stem:[Q_1 <= Q < Q_2]), the error
(of indication) curve shall not exceed a maximum error limit of stem:[pm 4 %]
for all temperature classes. For flow rates in the upper flow rate zone
(stem:[Q_2 <= Q <= Q_4]), the error (of indication) curve shall not exceed a
maximum error limit of stem:[pm 1.5 %] for meters of temperature class T30 and
stem:[pm 2.5 %] for all other temperature classes.
| | |
|===

<<<

[%unnumbered,cols="15a,45a,3a,3a,34a",options="header"]
|===
| OIML R 49-1:2024, subclause | Requirement | {plus} | − | Remarks

|
| For the purpose of these requirements, the arithmetic mean values of the errors
(of indication) stem:[bar(E)] for each flow rate shall apply.
| | |

| 7.2.6.3
| Accuracy class 2 meters

The variation in the error curve shall not exceed stem:[3 %] for flow rates
in the lower zone (stem:[Q_1 <= Q < Q_2]) and stem:[1.5 %] for flow rates in
the upper zone (stem:[Q_2 <= Q < Q_4]).

For flow rates in the lower flow rate zone (stem:[Q_1 <= Q < Q_2]), the error
(of indication) curve shall not exceed a maximum error limit of stem:[pm 6 %]
for all temperature classes. For flow rates in the upper flow rate zone
(stem:[Q_2 <= Q < Q_4]) the error (of indication) curve shall not exceed a maximum
error limit of stem:[pm 2.5 %] for meters of temperature class T30 and stem:[pm 3.5 %]
for all other temperature classes.

For the purpose of these requirements, the arithmetic mean value of the errors
(of indication) stem:[bar(E)] for each flow rate shall apply.
| | |

| 7.2.7
| Interchange error

It shall be demonstrated that cartridge meters and exchangeable metrological
modules for water meters with exchangeable metrological modules are independent
of the connection interfaces they are made for, as far as their metrological
performance is concerned. The cartridge meters and exchangeable metrological
modules shall be tested in accordance with the test specified in OIML R 49-2:2024,
7.4.6.
| | |

| 7.2.8
| Static magnetic field

All water meters where the mechanical components may be influenced by a static
magnetic field and all meters with electronic components shall be tested by
applying a specified field.

The test shall be carried out at stem:[Q_3] and show that the indications of
the installed water meter do not exceed MPEs of the upper zone according to
the accuracy class of the meter:
| | |
|===

<<<

[%unnumbered,cols="15a,45a,3a,3a,34a",options="header"]
|===
| OIML R 49-1:2024, subclause | Requirement | {plus} | − | Remarks

|
| Forward flow tests

Reverse flow tests (where applicable)

Application of the field in different planes

The test is specified in OIML R 49-2, 7.12.
| | |

5+| *Documentation*

| 7.2.9
| The application for type approval of a water meter or a calculator (including
indicating device) or a measurement transducer shall include the following documents:
| | |

| 7.2.9.1 a)
| a description giving the technical characteristics and the principle of operation;
| | |

| 7.2.9.1 b)
| a drawing or photograph of the complete water meter or calculator or measurement
transducer;
| | |

| 7.2.9.1 c)
| a list of the parts with a description of their constituent materials when
these parts have a metrological influence;
| | |

| 7.2.9.1 d)
| an assembly drawing with identification of the different parts;
| | |

| 7.2.9.1 e)
| for meters fitted with correction devices, a description of how the correction
parameters are determined;
| | |

| 7.2.9.1 f)
| a drawing showing the location of seals and verification mark(s);
| | |

| 7.2.9.1 g)
| a drawing of regulatory markings;
| | |

| 7.2.9.1 h)
| for combination meters that comprise approved meters, the test reports for
those meters;
| | |

| 7.2.9.1 i)
| optionally, a user guide and installation manual.
| | |

| 7.2.9.2
| In addition, the application for type approval of a water meter with electronic
devices shall include:
| | |

| 7.2.9.2 a)
| a functional description of the various electronic devices;
| | |

| 7.2.9.2 b)
| a flow diagram of the logic, showing the functions of the electronic devices;
| | |

| 7.2.9.2 c)
| any document or evidence which shows that the design and construction of the
water meter with electronic devices comply with the requirements of
| | |
|===

<<<

[%unnumbered,cols="15a,45a,3a,3a,34a",options="header"]
|===
| OIML R 49-1:2024, subclause | Requirement | {plus} | − | Remarks

|
| this part of OIML R 49-1, in particular OIML R 49-1:2024, 5.1 and Annex B.
| | |

| 7.2.9.3
| The applicant seeking type approval shall provide the body responsible for
the evaluation with a meter or a calculator (including indicating device) or
a measurement transducer which is representative of the final type, in addition
to the samples provided as per 7.2.2.
| | |

| | | | |
|===

=== Performance tests for electronic water meters and electronic devices fitted to mechanical meters

[%unnumbered,cols="15a,45a,3a,3a,34a",options="header"]
|===
| OIML R 49-1:2024, subclause | Requirement | {plus} | − | Remarks

5+| *Dry heat*

| A.5
| To verify compliance with the provisions in OIML R 49-1, 4.2 under conditions
of high temperature.

(see OIML R 49-2:2024, 8.2)
| | |

5+| *Cold*

| A.5
| To verify compliance with the provisions in OIML R 49-1, 4.2 under conditions
of low temperature.

(see OIML R 49-2:2024, 8.3)
| | |

5+| *Damp heat, cyclic, condensation*

| A.5
| To verify compliance with the provisions in OIML R 49-1, 5.1.1 under conditions
of high humidity when combined with cyclic temperature changes.

Cyclic tests shall be applied in all the cases where condensation is important
or when the penetration of vapour is accelerated by the breathing effect.

(see OIML R 49-2:2024, 8.4)
| | |
|===

<<<

[%unnumbered,cols="15a,45a,3a,3a,34a",options="header"]
|===
| OIML R 49-1:2024, subclause | Requirement | {plus} | − | Remarks

5+| *Power voltage variation, for water meters powered by DC batteries and DC mains*

| A.5
| To verify compliance with the provisions in OIML R 49-1, 4.2 under conditions
of varying DC voltage (if relevant).

(see OIML R 49-2:2024, 8.5)
| | |

5+| *Replaceable battery*

| 5.2.4
| To verify compliance with the provisions in OIML R 49-1, 5.2.4.3. The properties
and parameters of the meter shall not be affected by the interruption of the
electrical supply when the battery is replaced.

(see OIML R 49-2:2024, 8.5)
| | |

5+| *Power voltage variation, for water meters powered by direct AC or by AC/DC
converters*

| A.5
| To verify compliance with the provisions in OIML R 49-1, 4.2 under conditions
of varying AC mains power voltage (if relevant).

(see OIML R 49-2:2024, 8.5)
| | |

5+| *Vibration (random)*

| A.5
| To verify compliance with the provisions in OIML R 49-1, 5.1.1 under conditions
of random vibration.

(see OIML R 49-2:2024, 8.6)
| | |

5+| *Mechanical shock*

| A.5
| To verify compliance with the provisions in OIML R 49-1, 5.1.1 under conditions
of mechanical shocks.

(see OIML R 49-2:2024, 8.7)
| | |

5+| *Short time power reductions*

| A.5
| To verify compliance with the provisions in OIML R 49-1, 5.1.1 under conditions
of short time mains voltage reductions.

(see OIML R 49-2:2024, 8.8)
| | |
|===

<<<

[%unnumbered,cols="15a,45a,3a,3a,34a",options="header"]
|===
| OIML R 49-1:2024, subclause | Requirement | {plus} | − | Remarks

5+| *Bursts*

| A.5
| To verify compliance with the provisions in OIML R 49-1, 5.1.1 under conditions
where electrical bursts are superimposed on input/output and communication ports.

(see OIML R 49-2:2024, 8.9)
| | |

| A.5
| To verify compliance with the provisions in OIML R 49-1, 5.1.1 under conditions
where electrical bursts are superimposed on the mains voltage.

(see OIML R 49-2:2024, 8.10)
| | |

5+| *Electrostatic discharge*

| A.5
| To verify compliance with the provisions in OIML R 49-1, 5.1.1 under conditions
of direct and indirect electrostatic discharges.

(see OIML R 49-2:2024, 8.11)
| | |

5+| *Electromagnetic susceptibility -- electromagnetic fields*

| A.5
| To verify compliance with the provisions in OIML R 49-1, 5.1.1 under conditions
of radiated electromagnetic fields.

(see OIML R 49-2:2024, 8.12)
| | |

| A.5
| To verify compliance with the provisions in OIML R 49-1, 5.1.1 under conditions
of conducted electromagnetic fields.

(see OIML R 49-2:2024, 8.18)
| | |

| A.5
| To verify compliance with the provisions in OIML R 49-1, 5.1.1 under conditions
of mains power frequency electromagnetic field test.

(see OIML R 49-2:2024, 8.13)
| | |

5+| *Surges on signal, data, and control lines*

| A.5
| To verify compliance with the provisions in OIML R 49-1, 5.1.1 under conditions
where electrical
| | |
|===

<<<

[%unnumbered,cols="15a,45a,3a,3a,34a",options="header"]
|===
| OIML R 49-1:2024, subclause | Requirement | {plus} | − | Remarks

|
| surges are superimposed on I/O and communication ports.

(see OIML R 49-2:2024, 8.14)
| | |

5+| *Surges on AC and DC mains power lines*

| A.5
| To verify compliance with the provisions in OIML R 49-1, 5.1.1 under conditions
where electrical surges are superimposed on the mains voltage.

(see OIML R 49-2:2024, 8.15)
| | |

| | | | |
|===

Use this page to detail remarks from the checklist.
