== Withdrawal of an OIML Issuing Authority from the OIML-CS

=== {blank}

An OIML Issuing Authority may decide, for operational, business or commercial reasons, to withdraw as an OIML Issuing Authority from the OIML-CS, or to reduce their scope. In the event that an OIML Issuing Authority wishes to withdraw from the OIML-CS or to reduce their scope, the OIML Issuing Authority shall give notice to the Executive Secretary of its intention, but shall meet all current obligations to customers before actual withdrawal or reduction of scope.

=== {blank}

If the OIML Issuing Authority is withdrawn from the OIML-CS at the proposal of the Management Committee, any ongoing applications shall be completed under the conditions defined by the Management Committee. These conditions should take into account the fact that tests and examinations may already have started.

=== {blank}

In both cases, the Executive Secretary shall in turn notify the Utilizers and Associates who shall accept and utilise or recognise the OIML certificates and OIML type evaluation reports that were issued and registered prior to the withdrawal.
