== Foreword

The International Organization of Legal Metrology (OIML) is a worldwide, intergovernmental organization
whose primary aim is to harmonize the regulations and metrological controls applied by the national
metrological services, or related organizations, of its Member States. The main categories of OIML publications
are:

* *International Recommendations (OIML R)*, which are model regulations that establish the
metrological characteristics required of certain measuring instruments and which specify methods and
equipment for checking their conformity. OIML Member States shall implement these
Recommendations to the greatest possible extent;
* *International Documents (OIML D)*, which are informative in nature and which are intended to
harmonize and improve work in the field of legal metrology;
* *International Guides (OIML G)*, which are also informative in nature and which are intended to give
guidelines for the application of certain requirements to legal metrology; and
* *International Basic Publications (OIML B)*, which define the operating rules of the various OIML
structures and systems.

OIML Draft Recommendations, Documents and Guides are developed by Technical Committees or
Subcommittees which comprise representatives from the Member States. Certain international and regional
institutions also participate on a consultation basis. Cooperative agreements have been established between the
OIML and certain institutions, such as ISO and the IEC, with the objective of avoiding contradictory
requirements. Consequently, manufacturers and users of measuring instruments, test laboratories, etc. may
simultaneously apply OIML publications and those of other institutions.

International Recommendations, Documents, Guides and Basic Publications are published in English (E) and
translated into French (F) and are subject to periodic revision.

Additionally, the OIML publishes or participates in the publication of *Vocabularies (OIML V)* and periodically
commissions legal metrology experts to write *Expert Reports (OIML E)*. Expert Reports are intended to
provide information and advice, and are written solely from the viewpoint of their author, without the
involvement of a Technical Committee or Subcommittee, nor that of the CIML. Thus, they do not necessarily
represent the views of the OIML.

This publication - reference OIML R 138, Edition 2007 (E) - was developed by the OIML Technical
Subcommittee TC 8 _Measurement of quantities of fluids_. It was approved for final publication by the
International Committee of Legal Metrology in 2007 and will be submitted to the International Conference of
Legal Metrology in 2008 for formal sanction. This Edition replaces the previous editions of OIML R 4
_Volumetric flasks (one mark) in glass_ (Edition 1972), R 29 _Capacity serving measures_ (Edition 1979), R 45
_Casks and barrels_ (Edition 1980) and R 96 _Measuring container bottles_ (Edition 1990).

OIML Publications may be downloaded from the OIML web site in the form of PDF files. Additional
information on OIML Publications may be obtained from the Organization's headquarters:

Bureau International de Métrologie Légale +
11, rue Turgot - 75009 Paris - France +
Telephone: 33 (0)1 48 78 12 82 +
Fax: 33 (0)1 42 82 17 27 +
E-mail: biml@oiml.org +
Internet: www.oiml.org
