[[participation]]
== Participation in the OIML-CS

=== Type of participation

==== {blank}

The CIML Member in a given Member State may put forward to the Management Committee one or more OIML Issuing Authorities in that State per category of measuring instruments for its acceptance under Scheme A or Scheme B.

NOTE: An OIML Issuing Authority that issues OIML certificates may or may not be the same organisation as the national body that issues national type approval certificates and whose responsibilities are governed by national regulations.

==== {blank}

The CIML Member in a given Member State may designate one or more Utilizers in that State per category of measuring instrument.

==== {blank}

The OIML Corresponding Member Representative may designate one or more Associates in that country per category of measuring instrument.

==== {blank}

A list of all OIML Issuing Authorities and Utilizers in the various Member States and Associates from OIML Corresponding Members is maintained by the BIML and is permanently available to Member States, Corresponding Members and other interested parties on the OIML website and on request.

=== Competence requirements for OIML Issuing Authorities

OIML Issuing Authorities are required to demonstrate their competence through compliance with ISO/IEC 17065 <<ISO_IEC_17065>>.

=== Competence requirements for Test Laboratories

Test Laboratories are required to demonstrate their competence through compliance with ISO/IEC 17025 <<ISO_IEC_17025>>.

=== Demonstration of compliance

==== General

===== {blank}

The processes for the approval of OIML Issuing Authorities and Test Laboratories are specified in <<OIML_CS_PD_03>> and <<OIML_CS_PD_04>> respectively.

==== Scheme B

===== {blank}

For participation in Scheme B, OIML Issuing Authorities and Test Laboratories can demonstrate compliance on the basis of a self-declaration, with additional supporting evidence.

==== Scheme A

===== {blank}

For participation in Scheme A, compliance of OIML Issuing Authorities and Test Laboratories shall be demonstrated by peer evaluation, on the basis of an accreditation assessment or a peer assessment.

===== Accreditation of OIML Issuing Authorities

====== {blank}

Where accreditation is chosen by the OIML Issuing Authority, the Accreditation Body that carries out the accreditation assessment shall participate in a mutual recognition arrangement among Accreditation Bodies (regional or international), for instance the International Accreditation Forum (IAF) Multilateral Recognition Arrangement (MLA) footnote:[The International Accreditation Forum (IAF) and the International Laboratory Accreditation Cooperation (ILAC) will be replaced by a new organisation, the Global Accreditation Cooperation Incorporated. The target date (known as the Transition Date) for the new organisation to become operational and to take over the roles of IAF and ILAC is provisionally January 2026.].

====== {blank}

The accreditation assessment team shall comply with the requirements specified in Procedural Document <<OIML_CS_PD_03>>.

===== Accreditation of Test Laboratories

====== {blank}

The Accreditation Body that carries out the accreditation assessment of a Test Laboratory under the OIML-CS shall participate in a mutual recognition arrangement among Accrediting Bodies (regional or international), for instance the ILAC MRA (International Laboratory Accreditation Cooperation Mutual Recognition Arrangement)footnote:[See footnote 1.].

====== {blank}

The accreditation assessment team shall comply with the requirements specified in Procedural Document <<OIML_CS_PD_04>>.

===== Peer assessment for OIML Issuing Authorities and Test Laboratories

====== {blank}

Where the OIML Issuing Authority and/or Test Laboratory has chosen peer assessment, the peer assessment team shall comply with the requirements specified in Procedural Documents <<OIML_CS_PD_03>> and <<OIML_CS_PD_04>>, as appropriate.

=== OIML Issuing Authority Declaration

==== {blank}

OIML Issuing Authorities that have been accepted for participation in the OIML-CS (see 11.5 f)) sign a Declaration indicating their scope for issuing OIML certificates and OIML type evaluation reports under Scheme A and/or Scheme B. When an OIML Issuing Authority is accepted under Scheme A, the OIML Member State shall designate at least one Utilizer (see 5.6.1) for the respective category(ies) of measuring instrument(s).

NOTE: The requirement to designate at least one Utilizer shall not apply when the OIML Member State does not regulate that particular category of measuring instrument in their country.

=== Utilizers and Associates

==== {blank}

Utilizers sign a Declaration indicating their scope of acceptance of OIML certificates and/or OIML type evaluation reports issued under Scheme A and/or Scheme B. They may specify additional national requirements or special requirements which deviate from those in the relevant OIML Recommendation(s).

==== {blank}

Associates sign a Declaration indicating their scope of acceptance of OIML certificates and/or OIML type evaluation reports issued under Scheme A and/or Scheme B. They may specify additional national requirements or special requirements which deviate from those in the relevant OIML Recommendation(s).

==== {blank}

It is the responsibility of Utilizers and Associates to specify from which OIML Issuing Authorities and Test Laboratories they will accept evaluation reports, test reports and test data for additional national requirements. It is also the responsibility of Utilizers and Associates to specify whether they will accept OIML certificates and/or type evaluation reports issued on the basis of a test report(s) from a Manufacturer Test Laboratory. This information shall be provided in the Declaration of the Utilizer or Associate.

==== {blank}

The processes for the admission of Utilizers and Associates are specified in <<OIML_CS_PD_09>>.
