== Responsibilities of the BIML within the OIML-CS

=== {blank}

The BIML acts as the secretariat of the OIML-CS and undertakes the relevant administrative functions to support the operation of the OIML-CS, for example (but not limited to)

a) registering and publishing OIML certificates,

b) collecting OIML certificate registration fees, and

c) maintaining the OIML-CS pages on the OIML website.

=== {blank}

The Executive Secretary is a BIML staff member, appointed by the BIML Director. The Executive Secretary is responsible for the day-to-day operation of the OIML-CS under the direction of the Management Committee. The tasks and duties of the Executive Secretary are to

a) provide general administrative and secretarial services for the Management Committee, the Management Committee Working Groups, the Review Committee, the Test Laboratories Forum and the Board of Appeal;

b) organise meetings of the Management Committee, Management Committee Working Groups, Test Laboratories Forum and (where necessary) Board of Appeal;

c) process applications from OIML Issuing Authorities or Test Laboratories in accordance with the Operational and Procedural rules approved by the Management Committee;

d) provide advice on initial peer assessment and peer reassessment of OIML Issuing Authorities and Test Laboratories, including the selection of assessors;

e) maintain up to date records regarding the OIML Issuing Authorities and Test Laboratories;

f) maintain up to date records of Management Committee members and representatives of Test Laboratories in the Test Laboratories Forum;

g) assume responsibility for editing and organising the publication of OIML-CS publications;

h) assume responsibility for maintaining a list of Legal Metrology Experts and Management System Experts approved by the Management Committee;

i) monitor OIML-CS activities for reporting purposes; and

j) monitor the countries that have signed a Declaration.
