source "https://rubygems.org"

gem "metanorma-cli" #, github: "metanorma/metanorma-cli"
gem "mn2pdf", ">=2.52"
gem "metanorma-taste", github: "metanorma/metanorma-taste", branch: "main"

# WARNING: only for testing
# gem "html2doc", github: "metanorma/html2doc", branch: "main"
# gem "isodoc-i18n", github: "metanorma/isodoc-i18n", branch: "main"
# gem "isodoc", github: "metanorma/isodoc", branch: "main"
# gem "metanorma-standoc", github: "metanorma/metanorma-standoc", branch: "main"
# gem "metanorma", git: "https://github.com/metanorma/metanorma", branch: "main"
# gem "metanorma-iso", github: "metanorma/metanorma-iso", branch: "main"
# gem "metanorma-taste", github: "metanorma/metanorma-taste", branch: "main"
# gem "metanorma-utils", github: "metanorma/metanorma-utils", branch: "main"
# gem "relaton-render", "= 3.0.0.pre.alpha.19"
# #gem "fontist", github: "fontist/fontist", branch: "main"
# gem "mn2pdf"
# gem "debug"
# gem "sassc-embedded"
gem "relaton", "= 3.0.0.pre.alpha.11"
gem "relaton-bib", "2.2.0.pre.alpha.1"
gem "pubid", github: "pubid/pubid", branch: "main"
gem "moxml", github: "lutaml/moxml", branch: "main"
gem "leptris", "1.9.317"
