.Foreword

This publication has been prepared by the Maintenance Group of the OIML Certification System (OIML-CS) Management Committee.

The Management Committee approved this Edition 6 of OIML-CS PD-05 at its Ninth meeting on 06 March 2024 and it was published on 11 March 2024. This edition takes effect immediately upon publication.

Amendment 1 was issued on 27 August 2024 to correct an error in 5.4.1. The original text was:

[quote]
5.4.1 The provisions defined in 4.4.1, 4.4.3, 4.4.4 and 4.4.5 above apply.

The text has been amended to read:

[quote]
5.4.1 The provisions defined in 4.4.1, 4.4.3, 4.4.4, 4.4.5 and 4.4.6 above apply.

This publication is directly related to OIML B 18 _Framework for the OIML Certification System (OIML-CS)_ <<OIML_B_18>> which contains the framework for the operation of the OIML-CS.

The text of this publication is based on the following documents:

.Edition history
|===
|Edition |Document |Report on Voting/Acceptance

|PD-05 Edition 1        |PD-05 Edition 1        |Published July 2017
|PD-05 Edition 2        |PD-05 Edition 2        |Published 20 December 2018
|PD-05 Edition 3        |PD-05 Edition 3        |Published 26 February 2021
|PD-05 Edition 4        |PD-05 Edition 4        |Published 14 November 2022
|PD-05 Edition 5        |PD-05 Edition 5        |Published 16 January 2024
|PD-05 Edition 6        |PD-05 Edition 6        |Published 11 March 2024
|PD-05 Edition 6 Amd. 1 |PD-05 Edition 6 Amd. 1 |Published 27 August 2024
|===

== Introduction

The OIML certification System (OIML-CS) has been established

. to promote the global harmonisation, uniform interpretation and implementation of legal metrological requirements for measuring instruments and/or modules,

. to avoid unnecessary re-testing when obtaining national type evaluations and approvals, and to support the recognition of measuring instruments and/or modules under legal metrological control, while achieving and maintaining confidence in the results in support of facilitating the global trade of individual instruments, and

. to establish rules and procedures for fostering mutual confidence among participating OIML Member States and Corresponding Members in the results of type evaluations that indicate conformity of measuring instruments and/or modules, under legal metrological control, to metrological and technical requirements established in the applicable OIML Recommendation(s).

OIML B 18 _Framework for the OIML certification System (OIML-CS)_ <<OIML_B_18>> establishes the rules for a framework for the OIML-CS. OIML B 18 <<OIML_B_18>> is supplemented by a range of Operational Documents and Procedural Documents which are developed, maintained and approved by the OIML-CS Management Committee.
