== Rules

=== Travel

As soon as the CIML President is informed of the planned travel, the CIML President shall submit to
the BIML Director the following information:

. the foreseen dates of the travel (outward and return journeys);
. the means of travel (air, train, car);
. any need to purchase a modifiable ticket and the motivation for such a request;
. the reduced fares, if any, to which the CIML President is entitled on a personal basis;
. the accommodation already identified or suggested to him by the welcoming body and the rate
per night (specifying if partial-board is included).

=== Validation

The BIML Director shall validate the travel.

When validating, the BIML Director, or their representative, may modify the parameters of the travel,
in agreement with the person travelling.

=== Conditions

The CIML President shall propose the transportation mode, accommodation, timetable, and fares
following the principles below:

. the most economical journey is preferred, taking into account all modes of travel, travelling time
and modifiable tickets;
. the journey shall include no stops between the stations or airports servicing the CIML
President's departure point and the destination's nearest airport or station other than those
required by the trip connections, unless justified by professional motives or they allow a
reduction of the expenses incurred and the journey's length is not substantially modified;
. the journey may be extended, if this results in a reduction in overall costs which may include
additional accommodation and transportation;
. the journey, by rail when the connection exists, may be in first class;
. the journey by airplane shall be in economy class, except when any one section airtime of the
journey's duration is over seven hours. In this case, economy plus, when available, may be
authorised;
. a modifiable ticket may be granted where there is an actual uncertainty about the dates and/or
duration of the mission. Incurred taxes shall be paid by the BIML;
. luggage in excess of allowances shall be paid by the CIML President;
. the air and rail companies are selected in accordance with the above-mentioned principles and
after due consideration of the list of airlines banned within the European Union;
. the accommodation shall take into account the accommodations already identified or suggested
by the welcoming body and the nightly rate;
. a journey for personal motives may be combined with a mission. In this case, any extra fare for
the journey for personal motives shall not be paid or reimbursed by the BIML to the CIML
President;
. in the case that the CIML President is accompanied by other persons (spouse, parent, children,
etc., on a personal basis only), the costs incurred on the journey directly attributable to the
companion(s) will not be paid or reimbursed to the CIML President by the BIML. No liability
for the companion of the CIML President on travel during any journey is incurred by the BIML.

=== Cancelled journeys

The BIML shall pay for cancelled tickets and may pay for new tickets in the following cases:

. if the cancellation of the travel is decided by the Director or by the welcoming body and new
travel is required;
. if a force majeure event has occurred, i.e. unpredictable and beyond the control of the CIML
President, having prevented them from travelling and new travel is required;
. if the CIML President is unable to obtain a visa and new travel is required;
. if the flight or journey is cancelled by the airline or the rail company;
. if the planned connecting flights were rendered impossible by airline or rail company delays.

However, if the need to purchase new tickets originates solely as a result of the decision of the CIML
President, the BIML reserves the right to claim reimbursement from the CIML President of such tickets.

=== Per diem and reimbursable fees

According to the BIML Travel Policy, per diem may be provided to the CIML President when on travel
to a legal metrology related event.

The following fees shall be reimbursed, subject to the submission of receipts within thirty working days
following the day on which the CIML President returns from travel:

. the fees related to receptions and dinners organised in the attended event, if not included in the
general fees paid by the BIML before the travel;
. registration fees to attend the event to which the CIML President is invited;
. accommodation fees (including breakfast);
. local transportation fees.

Expenses incurred in a currency other than the Euro are reimbursed at the exchange rate on the date of
payment of the actual expense. Refer to http://www.xe.com/ucc/ . If paid with a credit card belonging
to the CIML President, an adjustment may be made, if necessary, between the justified expenditures and
the actual bank debit, upon submission of the debit memo of the bank holding the account.
