
[[annex-b]]
[appendix,obligation="informative"]
== Checking facilities

[[scls-B-1]]
=== Action of checking facilities

The detection by the checking facilities of significant faults shall result
in the following actions, according to the type.

For checking facilities of type P or type I:

. there shall be automatic correction of the fault; or
. only the faulty device shall stop if a water meter without that device continues
to comply with the regulations; or
. there shall be a visible or audible alarm; this alarm shall continue until
the cause of the alarm is resolved. Once the cause of the alarm is resolved
the alarm may be reset either manually or automatically.

In addition, when a water meter transmits data to peripheral equipment, the
transmission shall be accompanied by a message indicating the presence of a
fault. (This requirement is not applicable to the application of disturbances
specified in <<scls-A-5>>.)

The instrument may also be provided with devices to estimate the volume of water
having passed through the installation during the occurrence of the fault.
The result of this estimate shall not be capable of being mistaken for a valid
indication.

NOTE: The transmission of the alarm and repeated measured values from a meter
to the remote station need not be secured if the measured values are repeated
at that station.

[[scls-B-2]]
=== Checking facilities for the measurement transducer

[[scls-B-2-1]]
==== {blank}

The objective of these checking facilities is to verify the presence of the
measurement transducer, its correct operation and the correctness of data transmission.

The verification of correct operation includes detection or prevention of reverse
flow. However, it is not necessary for the detection or prevention of reverse
flow to be operated electronically.

[[scls-B-2-2]]
==== {blank}

When the signals generated by the flow sensor are in the form of pulses, each
pulse representing an elementary volume, the pulse generation, transmission
and counting shall fulfil the following tasks:

. correct counting of pulses;
. detection of reverse flow, if necessary;
. checking of correct function.

This may be done by means of:

[arabic]
. three-pulse system with use of either pulse edges or pulse status;
. double-pulse line system with use of pulse edges plus pulse status;
. double-pulse system with positive and negative pulses depending on the flow
direction.

These checking facilities shall be of type P.

It shall be possible during type evaluation to verify that these checking facilities
function correctly:

[lowerroman]
. by disconnecting the transducer; or
. by interrupting one of the sensor's pulse generators; or
. by interrupting the electrical supply of the transducer.

[[scls-B-2-3]]
==== {blank}

For electromagnetic meters only, where the amplitude of the signals generated
by the measurement transducer is proportional to the flow rate, the following
procedure may be used.

A simulated signal with a shape similar to that of the measurement signal is
fed into the input of the secondary device, representing a flow rate between
the minimum and maximum flow rates of a meter. The checking facility shall check
the primary and the secondary device. The equivalent digital value is checked
to verify that it is within predetermined limits given by the manufacturer and
consistent with the MPEs. This checking facility shall be of type P or
type I. For type I facilities, checking shall occur at least every stem:[5 "unitsml(min)"].

NOTE: Following this procedure, additional checking facilities (more than two
electrodes, double signal transmission, etc.) are not required.

[[scls-B-2-4]]
==== {blank}

The maximum permissible cable length between primary and secondary devices of
an electromagnetic meter, as defined in <<ISO_6817_1992>> shall be not more
than stem:[100 "unitsml(m)"] or not more than the value stem:[L] expressed in
metres according to the following formula, whichever is smaller:

[[formula-B-1]]
[stem]
++++
L = (k sigma)/(f C)
++++

where

stem:[k]:: is equal to stem:[2 xx 10^{-5} "unitsml(m)"];
stem:[sigma]:: is the conductivity of the water, in stem:["unitsml(S/m)"];
stem:[f]:: is the field frequency during the measuring cycle, in stem:["unitsml(Hz)"];
stem:[C]:: is the effective cable capacitance per metre, in stem:["unitsml(F/m)"].

It is not necessary to fulfil these requirements if the manufacturer's solutions
ensure equivalent results.

[[scls-B-2-5]]
==== {blank}

For other technologies, checking facilities providing equivalent levels of security
remain to be developed.

[[scls-B-3]]
=== Checking facilities for the calculator

[[scls-B-3-1]]
==== {blank}

The objective of these checking facilities is to verify that the calculator
system functions correctly and to ensure the validity of the calculations made.

No special means are required for indicating that these checking facilities
function correctly.

[[scls-B-3-2]]
==== {blank}

The checking facilities for the functioning of the calculation system shall
be of type P or type I. For type I the checking shall occur at least either
once per day or for every volume equivalent to stem:[10 "unitsml(min)"] of flow
at stem:[Q_3]. The objective of this checking facility is to verify that:

. the values of all permanently memorized instructions and data are correct,
by such means as:
+
--
[arabic]
. summing up all instruction and data codes and comparing the sum with a fixed
value;
. line and column parity bits (longitudinal redundancy check and vertical redundancy
check);
. cyclic redundancy check (CRC 16);
. double independent storage of data;
. storage of data in "`safe coding`", e.g. protected by checksum, line and column
parity bits;
--
. all procedures of internal transfer and storage of data relevant to the measurement
result are performed correctly, by such means as:
+
--
[arabic]
. write--read routine;
. conversion and re-conversion of codes;
. use of "`safe coding`" (checksum, parity bit);
. double storage.
--

[[scls-B-3-3]]
==== {blank}

The checking facilities for the validity of calculations shall be of type P
or type I. For type I the checking shall occur either at least once per day,
or for every volume equivalent to stem:[10 "unitsml(min)"] of flow at stem:[Q_3].

This consists of checking the correct value of all data related to the measurement
whenever these data are internally stored or transmitted to peripheral equipment
through an interface. This check may be carried out by such means as parity
bit, check sum or double storage. In addition, the calculation system shall
be provided with a means of controlling the continuity of the calculation programme.

[[scls-B-4]]
=== Checking facility for the indicating device

[[scls-B-4-1]]
==== {blank}

The objective of this checking facility is to verify that the primary indications
are displayed and that they correspond to the data provided by the calculator.
In addition, it aims at verifying the presence of the indicating devices when
they are removable. These checking facilities shall have either the form as
defined in <<scls-B-4-2>> or that as defined in <<scls-B-4-3>>.

[[scls-B-4-2]]
==== {blank}

The checking facility of the indicating device is of type P; however, it may
be of type I if a primary indication is provided by another device.

Means may include, for example:

. for indicating devices using incandescent filaments or light emitting diodes,
measuring the current in the filaments;
. for indicating devices using fluorescent tubes, measuring the grid voltage;
. for indicating devices using multiplexed liquid crystals, output checking
of the control voltage of segment lines and of common electrodes, so as to detect
any disconnection or short circuit between control circuits.

The checks mentioned in <<scls-6-7-2-2>> are not necessary.

[[scls-B-4-3]]
==== {blank}

The checking facility for the indicating device shall include type P or
type I checking of the electronic circuits used for the indicating device
(except the driving circuits of the display itself); this checking facility
shall meet the requirements of <<scls-B-3-3>>.

[[scls-B-4-4]]
==== {blank}

It shall be possible during type evaluation to determine that the checking facility
of the indicating device is working, either:

. by disconnecting all or part of the indicating device; or
. by an action which simulates a failure in the display, such as using a test
button.

[[scls-B-4-5]]
==== {blank}

Although the continuous display of volume is not mandatory (see <<scls-4-3-5>>),
interruption of the display shall not interrupt the action of checking facilities.

[[scls-B-5]]
=== Checking facilities for ancillary devices

An ancillary device (repeating device, printing device, memory device, etc.)
with primary indications shall include a checking facility of type P or
type I. The aim of this checking facility is to verify the presence of the ancillary
device, when it is a necessary device, and to verify correct functioning and
correct transmission.

[[scls-B-6]]
=== Checking facilities for the associated measuring instruments

Associated measuring instruments shall include a checking facility of type P
or type I. The aim of this checking facility is to ensure that the signal given
by these associated instruments is inside a predetermined measuring range.

[example]
====
Four wire transmission for resistance type temperature sensors; control of the
driving current for stem:[4 "unitsml(mA)"] -- stem:[20 "unitsml(mA)"] pressure
sensors.
====
