.Foreword

This publication has been prepared by the Maintenance Group of the OIML Certification System (OIML-CS) Management Committee.

The Management Committee approved this Edition 4 of OIML-CS PD-06 at its Ninth meeting on 06 March 2024 and it was published on 11 March 2024. This edition takes effect immediately upon publication.

This publication is directly related to the Framework for the OIML Certification System (OIML-CS) (OIML B 18 <<OIML_B_18>>) which contains the framework for the operation of the OIML-CS.

The text of this publication is based on the following documents:

.Edition history
|===
|Edition |Document |Report on Voting/Acceptance

|PD-06 Edition 1 |PD-06 Edition 1 |Published July 2017
|PD-06 Edition 2 |PD-06 Edition 2 |Published 20 December 2018
|PD-06 Edition 3 |PD-06 Edition 3 |Published 26 February 2021
|PD-06 Edition 4 (Draft) |OIML-CS_SC3_P1_SG3_N088 |Draft for MG comment – 20231213
|PD-06 Edition 4 (draft) |OIML-CS_SC1_P1_N414 |Draft for MC vote – 20240228
|===

== Introduction

=== {blank}

The OIML certification System (OIML-CS) has been established

. to promote the global harmonization, uniform interpretation and implementation of legal metrological requirements for measuring instruments and/or modules,

. to avoid unnecessary re-testing when obtaining national type evaluations and approvals, and to support the recognition of measuring instruments and/or modules under legal metrological control, while achieving and maintaining confidence in the results in support of facilitating the global trade of individual instruments, and

. to establish rules and procedures for fostering mutual confidence among participating OIML Member States and Corresponding Members in the results of type evaluations that indicate conformity of measuring instruments and/or modules, under legal metrological control, to metrological and technical requirements established in the applicable OIML Recommendation(s).

=== {blank}

OIML B 18 Framework for the OIML certification System (OIML-CS) <<OIML_B_18>> establishes the rules for a framework for the OIML-CS. OIML B 18 <<OIML_B_18>> is supplemented by a range of Operational Documents and Procedural Documents which are developed, maintained and approved by the OIML-CS Management Committee.
