== Misuse of an OIML certificate by its owner

=== {blank}

The Executive Secretary shall consult the CIML Member of the Member State in which an OIML certificate was issued when documented and substantiated evidence is presented that the OIML certificate is being used by its owner in a manner contrary to the requirements of clause 4. Depending on the conclusions of the consultation, the Executive Secretary shall inform the Management Committee, other Member States, the OIML Issuing Authority and interested parties accordingly and also directly inform the owner that continued misuse of the OIML certificate will lead to corrective actions being taken by the Management Committee that could result in the OIML certificate being deregistered by the BIML.

=== {blank}

In the event of a proposal to deregister the OIML certificate the owner of the OIML certificate may appeal this decision according to the procedure defined in Procedural Document PD-01 <<OIML_CS_PD_01>>.

=== {blank}

If the appeal is not upheld and the OIML certificate is to be deregistered, the Executive Secretary shall notify the owner of the OIML certificate, inform the Management Committee, Member States, the OIML Issuing Authority and any other interested parties, and publish a notice in appropriate publications including the OIML Bulletin and the OIML website.
