== Use of an OIML certificate and OIML Type Evaluation Report

=== {blank}

An OIML certificate issued by an OIML Issuing Authority under Scheme A or B
of the OIML-CS does not bestow any form of legal international approval.

=== {blank}

The owner may use a registered OIML certificate and its associated OIML type
evaluation report as follows:

. in support of an application for national or regional type approval in any
country or group of countries; it is the responsibility of the applicant to
give evidence upon request that the type presented for approval is identical
to that identified on the OIML certificate;
+
NOTE: If requested by the regional or national approval authority, the complete
OIML type evaluation report shall be presented by, or on behalf of, the owner
together with the OIML certificate.

. in support of the presentation of an individual instrument for initial verification
in a country in which type approval is not required; it is the responsibility
of the applicant to give evidence upon request that the instrument presented
for verification is of the type that is identified on the OIML certificate;

. to inform buyers, users, and other interested parties that the type of measuring
instrument (represented by the tested samples) was found to conform to the requirements
of the relevant Recommendation.
+
NOTE: Such evidence of conformity (and the name of the OIML Issuing Authority
which issued the OIML certificate) may be referred to or included in e.g. manufacturer's
catalogues and other marketing literature (however, see <<use_of_certificates,
4.4 and 4.5>>).
+
NOTE: In some countries it is an offense to sell instruments that do not conform
with the certified type.

=== {blank}

If requested by the regional or national issuing authority, the owner is responsible
for providing the Utilizer or Associate with the original, or a certified copy
of, the complete OIML type evaluation report and the associated test reports.

=== {blank}

An OIML certificate shall not be used as proof of conformity of an individual
instrument with the requirements of the relevant Recommendation.

The OIML or OIML-CS logos shall not be affixed to an individual measuring instrument.
Requirements regarding the use of the OIML and OIML-CS logo are specified in <<OIML_B_20>>.

[[use_of_certificates]]
=== {blank}

Apart from the mention of the OIML certificate number with the name of the OIML
Issuing Authority which issued the OIML certificate, partial quotation of the
OIML certificate or of the associated OIML type evaluation report is not permitted,
though they may be reproduced in full.

=== {blank}

The legal metrology service (or other responsible body) to which the application
for national or regional type approval is made should take into consideration
the OIML certificate and its associated OIML type evaluation report to the extent
that is possible.

=== {blank}

OIML Members are encouraged to adopt mechanisms to recognize and accept OIML
certificates and their associated OIML type evaluation reports issued under
Scheme B of the OIML-CS through appropriate measures.

=== {blank}

In the event that questions arise during the review of an OIML certificate and
OIML type evaluation report received (including the test data), a Utilizer or
Associate shall consult the relevant OIML Issuing Authority for clarification
of the matter and take any further appropriate actions. In case the test data
are not accepted, written justification for denial shall be sent to the relevant
OIML Issuing Authority, the manufacturer and the Executive Secretary. The OIML
Issuing Authority may subsequently appeal this decision according to the procedure
defined in Procedural Document <<OIML_CS_PD_01>>.

=== {blank}

OIML type evaluation reports that contain test results from a Manufacturer Test
Laboratory (MTL) may be accepted by Utilizers and Associates on a voluntary
basis. In the event that test results from an MTL are not accepted, a justification
or explanation is not required.
