== Foreword

=== Foreword by the OIML

The International Organization of Legal Metrology (OIML) is a worldwide, intergovernmental organization
whose primary aim is to harmonize the regulations and metrological controls applied by the national
metrological services, or related organizations, of its Member States. The main categories of OIML publications
are:

* *International Recommendations (OIML R)*, which are model regulations that establish the
metrological characteristics required of certain measuring instruments and which specify methods and
equipment for checking their conformity. OIML Member States shall implement these
Recommendations to the greatest possible extent;
* *International Documents (OIML D)*, which are informative in nature and which are intended to
harmonize and improve work in the field of legal metrology;
* *International Guides (OIML G)*, which are also informative in nature and which are intended to give
guidelines for the application of certain requirements to legal metrology; and
* *International Basic Publications (OIML B)*, which define the operating rules of the various OIML
structures and systems.

OIML Draft Recommendations, Documents and Guides are developed by Technical Committees or
Subcommittees which comprise representatives from the Member States. Certain international and regional
institutions also participate on a consultation basis. Cooperative agreements have been established between the
OIML and certain institutions, such as ISO and the IEC, with the objective of avoiding contradictory
requirements. Consequently, manufacturers and users of measuring instruments, test laboratories, etc. may
simultaneously apply OIML publications and those of other institutions.

International Recommendations, Documents, Guides and Basic Publications are published in English (E) and
translated into French (F) and are subject to periodic revision.

Additionally, the OIML publishes or participates in the publication of *Vocabularies (OIML V)* and periodically
commissions legal metrology experts to write *Expert Reports (OIML E)*. Expert Reports are intended to
provide information and advice, and are written solely from the viewpoint of their author, without the
involvement of a Technical Committee or Subcommittee, nor that of the CIML. Thus, they do not necessarily
represent the views of the OIML.

This publication - reference OIML E 6, edition 2011 (E) - was written by Mr. George M. Teunisse, Department
of Legal Affairs, Verispect B.V., Department V-JZ, PO Box 654, NL-2600 AR Delft, The Netherlands.
Mr. Teunisse is the OIML contact person for Technical Work for The Netherlands and he was the Convenor of
an ad-hoc working group established after the OIML seminar on smart meters (Brijuni, 2-5 June 2009) to
develop this publication.

OIML Publications may be downloaded from the OIML web site in the form of PDF files. Additional
information on OIML Publications may be obtained from the Organization's headquarters:

Bureau International de Métrologie Légale +
11, rue Turgot - 75009 Paris - France +
Telephone: 33 (0)1 48 78 12 82 +
Fax: 33 (0)1 42 82 17 27 +
E-mail: biml@oiml.org +
Internet: www.oiml.org

=== Foreword by the Author

The OIML Seminar on Smart Meters, which took place in Brijuni, Croatia on 2-5 June 2009,
was organized to bring together relevant stakeholders in the legal metrological aspects of
smart metering: manufacturers, users (utilities and consumers), authorities (regulators,
inspectorates), and conformity assessment bodies, together with the Secretariats of the
relevant OIML Technical Committees and Subcommittees.

The Seminar was hosted by the Croatian State Office for Metrology, and its main purpose was
to enable the OIML to take note of recent developments in smart metering (technologies and
regulations, experiences and lessons learned) and to investigate the impact on the
international harmonization of legal requirements for utility meters.

Fifty experts from 23 countries participated, representing national authorities, the European
Commission, industry, standardization bodies, OIML Technical Committees and
Subcommittees, and the BIML.

After a series of presentations and discussions, the following two main conclusions were
drawn:

. *For utility meters, it is the opinion of the participants that metrological control
extends to the point where the consumer can verify that the measurement results
used for billing are consistent with the reading of the meter.*
. *As a follow-up to this Seminar, it would be appropriate for the OIML to develop
some kind of guidance paper for those OIML Technical Committees and
Subcommittees that deal with utility meters, containing suggestions for the
application of OIML Documents D 11:2004 _General requirements for electronic
measuring instruments_ and D 31:2008 _General requirements for software
controlled measuring instruments_ to utility meters and for additional
requirements and (immunity) tests to be considered.*

It was suggested that the task of developing such a guidance paper could be performed by an
ad-hoc working group. Considering the time constraints and the limited 'shelf life' of such a
guidance paper, it was considered more efficient to publish it as an OIML Expert Report
rather than to allocate this task to an existing OIML TC/SC as a new work item.

CIML Members were therefore invited to nominate experts to participate in the WGSM
(_Working Group on Smart Meters_); experts were required to have appropriate experience
relevant to the subject (i.e. legal metrological requirements for, and testing of, utility meters).

The outcome of the work of the WGSM is hereby published in the form of this Expert Report,
which should be considered as the expression of expert opinion to provide guidance to the
relevant OIML Technical Committees and Subcommittees in implementing requirements for
measuring instruments having remote control and/or reading of data. The content of this
Report is not specifically restricted to utility meters but should be especially helpful in the
development of new Recommendations or the revision of existing Recommendations on such
measuring instruments. It provides the necessary information on how to accomplish the
relevant OIML objectives and explains how to decide whether to include additional
performance requirements.

In Chapter 5 a rationale containing considerations, assumptions, restrictions, and statements is
presented containing the current approaches presented in OIML publications that are
considered applicable to smart meters and smart meter systems.

Chapter 6 describes a further legal metrology approach in general terms of the smart meter
system as a whole, taking into account its environment of use.

Chapter 7 further focuses on the more practical evaluation by subdividing the system into a
number of "black boxes" and discusses the practical way of evaluating and establishing the
required tests.

This first edition of the Expert Report is intended to give some initial guidance. Readers are
requested to collect comments and experiences when implementing legal requirements for
these complex interconnected measurement systems. Feedback will be of great value for
future editions of this Report and should be addressed to the author Mr. George Teunisse
(gteunisse@verispect.nl) with a copy to the BIML (willem.kool@oiml.org).
