
== Foreword

The International Organization of Legal Metrology (OIML) is a worldwide, intergovernmental
organization whose primary aim is to harmonize the regulations and metrological
controls applied by the national metrological services, or related organizations,
of its Member States. The main categories of OIML publications are:

* *International Recommendations (OIML R),* which are model regulations that
establish the metrological characteristics required of certain measuring instruments
and which specify methods and equipment for checking their conformity. OIML
Member States shall implement these Recommendations to the greatest possible extent;

* *International Documents (OIML D),* which are informative in nature and which
are intended to harmonize and improve work in the field of legal metrology;

* *International Guides (OIML G),* which are also informative in nature and
which are intended to give guidelines for the application of certain requirements
to legal metrology; and

* *International Basic Publications (OIML B),* which define the operating rules
of the various OIML structures and systems.

OIML Draft Recommendations, Documents and Guides are developed by Project Groups
linked to Technical Committees or Subcommittees which comprise representatives
from the Member States. Certain international and regional institutions also
participate on a consultation basis. Cooperative agreements have been established
between the OIML and certain institutions, such as ISO and the IEC, with the
objective of avoiding contradictory requirements. Consequently, manufacturers
and users of measuring instruments, test laboratories, etc. may simultaneously
apply OIML publications and those of other institutions.

International Recommendations, Documents, Guides and Basic Publications are
published in English (E) and translated into French (F) and are subject to periodic
revision.

Additionally, the OIML publishes or participates in the publication of *Vocabularies
(OIML V)* and periodically commissions legal metrology experts to write *Expert
Reports (OIML E)*. Expert Reports are intended to provide information and advice,
and are written solely from the viewpoint of their author, without the involvement
of a Technical Committee or Subcommittee, nor that of the CIML. Thus, they do
not necessarily represent the views of the OIML.

This publication – reference OIML R 91-4, Edition 2025 – was developed by Project
Group 3 of OIML Technical Subcommittee TC 7/SC 4 _Measuring instruments for
road traffic_. It was approved for final publication by the International Committee
of Legal Metrology at its 60th meeting in October 2025. It supersedes the previous
edition of OIML R 91 dated 1990.

There was also a change of title of the publication from "Radar equipment for
the measurement of the speed of vehicles" to "Traffic speed meters" to make
the publication as general as is possible regarding the different technologies
implemented in the measuring principle.

OIML Publications may be downloaded from the OIML web site in the form of PDF
files. Additional information on OIML Publications may be obtained from the
Organization's headquarters:

Bureau International de Métrologie Légale +
11, rue Turgot - 75009 Paris - France +
Telephone: 33 (0)1 48 78 12 82 +
Fax: 33 (0)1 42 82 17 27 +
E-mail: biml@oiml.org +
Internet: www.oiml.org

== Introduction

The "Type evaluation report", the subject of OIML R 91-4, aims at presenting,
in a standardized format, the results of the evaluation to which a type of a
speed meter shall be submitted with a view to its approval.

The "Checklist" is a summary of the evaluation and examinations carried out
on the instrument. It includes the conclusions of the results of the tests performed,
experimental or visual checks based on the required performance criteria and
associated tests in OIML R 91-1 and -2. The words or condensed sentences intend
to remind the examiner of the requirements of R 91-1 and -2 without reproducing them.

All metrology services evaluating types of speed meters according to OIML R
91-1 and -2 or to national or regional regulations based on OIML R 91-1 and -2
are strongly advised to use this "Type evaluation report format", directly or
after translation into a language other than English or French. Its direct use
in English or in French, or in both languages, is even more strongly recommended
whenever the results of type evaluation may be transmitted by the country performing
these evaluations to the approving authorities of another country, under bi-
or multi-lateral cooperation agreements. In the framework of the OIML Certification
System (OIML-CS), use of the "Type evaluation report format" is mandatory.
