
[[cls-2]]
== METROLOGICAL REQUIREMENTS

=== Accuracy classes

[[scls-2-1-1]]
==== Vehicle mass

For determining the vehicle mass, WIM instruments are divided into six accuracy
classes as shown below:

[align=center]
0.2 0.5 1 2 5 10

NOTE: The limitation of accuracy classes to certain applications may be determined
by national regulations.

==== Single-axle load and axle-group load

For determining single-axle load and, if required axle-group load, WIM instruments
are divided into six accuracy classes as shown below:

[align=center]
A B C D E F

NOTE: WIM instruments may have different accuracy classes for single-axle load
and axle-group load.

NOTE: The limitation of accuracy classes to certain applications may be determined
by national regulation.

==== Relationship between accuracy classes

The relationship between the accuracy classes for single-axle load and, if required,
axle-group load and the accuracy classes for vehicle mass are as specified in
<<table-1>> below.

[[table-1]]
[cols="7*^.^",options="header",headerrows=2]
|===
.2+| Accuracy class single-axle load and axle-group load
6+| Accuracy class for vehicle mass
| 0.2 | 0.5 | 1 | 2 | 5 | 10

| A | ✓ | ✓ | | | |
| B | ✓ | ✓ | ✓ | | |
| C | | ✓ | ✓ | ✓ | |
| D | | | ✓ | ✓ | ✓ |
| E | | | | ✓ | ✓ | ✓
| F | | | | | | ✓
|===

[[scls-2-2]]
=== Limits of error

==== Weighing-in-motion

===== Vehicle mass

The maximum permissible error for the vehicle mass determined by in-motion weighing,
shall be one of the following values, whichever is greater:

. the value calculated according to <<table-2>>, rounded to the nearest scale
interval;
. stem:[1 d xx] the number of axles in the totalization in the case of initial
verification, +
stem:[2 d xx] the number of axles in the totalization in the case of in-service
inspection.

[[table-2]]
[cols="3*^",options="header",headerrows=2]
|===
.2+| Accuracy class for vehicle mass
2+| Percentage of conventional value of the vehicle mass (<<scls-6-7>>)
| Initial verification | In-service inspection

| 0.2 | stem:[pm 0.10 %] | stem:[pm 0.20 %]
| 0.5 | stem:[pm 0.25 %] | stem:[pm 0.50 %]
| 1   | stem:[pm 0.50 %] | stem:[pm 1.00 %]
| 2   | stem:[pm 1.00 %] | stem:[pm 2.00 %]
| 5   | stem:[pm 2.50 %] | stem:[pm 5.00 %]
| 10  | stem:[pm 5.00 %] | stem:[pm 10.00 %]
|===

[[scls-2-2-1-2]]
===== Single-axle load and axle-group load

The limits of error applicable to single-axle loads and, if required, axle-group
loads are as follows:

. [[item-2-2-1-2-a]]For static reference single-axle loads of the two-axle
rigid reference vehicle, the applicable limits of error are as specified in
<<scls-2-2-1-2-1>>.
. [[item-2-2-1-2-b]]For all other reference vehicle single-axle loads and
axle-group loads, the applicable limits of error are as specified in
<<scls-2-2-1-2-2>>.


[[scls-2-2-1-2-1]]
====== Maximum permissible error for two-axle rigid reference vehicle

For the two-axle rigid reference vehicle, the maximum difference between the
indicated single-axle load for in-motion tests and the conventional true value
of the static reference single-axle load shall not exceed one of the following
values, whichever is the greater:

. The value from <<table-3>> rounded to the nearest scale interval.
. stem:[1 d] in the case of initial verification, +
stem:[2 d] in the case of in-service inspection.

[[table-3]]
[cols="3*^",options="header",headerrows=2]
|===
.2+| Accuracy class for single-axle load
2+| Percentage of conventional true value of the static reference single-axle load
| Initial verification | In-service inspection

| A | stem:[pm 0.25 %] | stem:[pm 0.50 %]
| B | stem:[pm 0.50 %] | stem:[pm 1.00 %]
| C | stem:[pm 0.75 %] | stem:[pm 1.50 %]
| D | stem:[pm 1.00 %] | stem:[pm 2.00 %]
| E | stem:[pm 2.00 %] | stem:[pm 4.00 %]
| F | stem:[pm 4.00 %] | stem:[pm 8.00 %]
|===

[[scls-2-2-1-2-2]]
====== Maximum permissible deviation (MPD) for all reference vehicle types except the two-axle rigid reference vehicle

For all reference vehicle types except the two-axle rigid reference vehicle,
the maximum difference between any indicated single-axle load or, if required,
any axle-group load recorded during in-motion tests and the corrected mean single-axle
load (<<scls-6-10>>) or the corrected mean axle-group load (<<scls-6-11>>),
respectively, shall be one of the following values, whichever is the greater:

. The value from <<table-4>> rounded to the nearest scale interval;
. stem:[1 d xx n] in the case of initial verification, +
stem:[2 d xx n] in the case of in-service inspection, +
Where stem:[n] is the number of axles in the group, with stem:[n = 1] for single
axles.

[[table-4]]
[cols="3*^",options="header",headerrows=2]
|===
.2+| Accuracy class for single-axle load and axle-group load
2+| Percentage of the corrected mean single-axle load or corrected mean axle-group
load
| Initial verification | In-service inspection

| A | stem:[pm 0.50 %] | stem:[pm 1.00 %]
| B | stem:[pm 1.00 %] | stem:[pm 2.00 %]
| C | stem:[pm 1.50 %] | stem:[pm 3.00 %]
| D | stem:[pm 2.00 %] | stem:[pm 4.00 %]
| E | stem:[pm 4.00 %] | stem:[pm 8.00 %]
| F | stem:[pm 8.00 %] | stem:[pm 16.00 %]
|===

[[scls-2-2-2]]
==== Static weighing

The maximum permissible errors on static weighing for increasing or decreasing
loads shall be the appropriate values in <<table-5>>.

[[table-5]]
[cols="4*^",options="header",headerrows=2]
|===
.2+| Accuracy class for vehicle mass
.2+| Load, stem:[m], expressed in scale intervals
2+| Maximum permissible errors
| Initial verification | In-service inspection

.3+^.^| 0.2 0.5 1
| stem:[0 <= m <= 500]    | stem:[pm 0.5 d] | stem:[pm 1.0 d]
| stem:[500 < m <= 2000]  | stem:[pm 1.0 d] | stem:[pm 2.0 d]
| stem:[2000 < m <= 5000] | stem:[pm 1.5 d] | stem:[pm 3.0 d]

.3+^.^| 2 5 10
| stem:[0 <= m <= 50]    | stem:[pm 0.5 d] | stem:[pm 1.0 d]
| stem:[50 < m <= 200]   | stem:[pm 1.0 d] | stem:[pm 2.0 d]
| stem:[200 < m <= 1000] | stem:[pm 1.5 d] | stem:[pm 3.0 d]
|===

NOTE: See <<table-1>> for the relationship between the accuracy classes for
vehicle mass and the accuracy classes for single-axle load and, if required,
axle-group load.

[[scls-2-3]]
=== Scale interval, stem:[d]

For a particular method of weighing-in-motion and combination of load receptors,
all load indicating and printing devices on an instrument shall have the same
scale interval.

The relationship among the accuracy class, the value of the scale interval and
the number of scale intervals for the maximum capacity of the instrument shall
be as specified in <<table-6>>.

[[table-6]]
[cols="4*^",options="header"]
|===
| Accuracy class for vehicle mass
| stem:[d] +
(stem:["unitsml(kg)"])
| Minimum number of scale intervals
| Maximum number of scale intervals

| 0.2 | stem:[<= 5]
.3+^.^| 500 .3+^.^| stem:[5000]

| 0.5 | stem:[<= 10]
| 1 | stem:[<= 20]

| 2 | stem:[<= 50]
.3+^.^| 50 .3+^.^| stem:[1000]

| 5 | stem:[<= 100]
| 10 | stem:[<= 200]
|===

NOTE: See <<table-1>> for the relationship between the accuracy classes for
vehicle mass and the accuracy classes for single-axle load and, if required,
axle-group load.

The scale intervals of the indicating or printing devices shall be in the form
stem:[1 xx 10^k], stem:[2 xx 10^k] or stem:[5 xx 10^k], stem:[k] being a positive
or negative whole number or zero.

[[scls-2-4]]
=== Minimum capacity

The minimum capacity shall not be less than the load, expressed in scale intervals,
specified in <<table-7>>.

[[table-7]]
[cols="4*^",options="header"]
|===
3+| Accuracy class for vehicle mass
| Minimum capacity in scale intervals
| 0.2 | 0.5 | 1  | 50
| 2   | 5   | 10 | 10
|===

NOTE: See <<table-1>> for the relationship between the accuracy class for vehicle
mass and the accuracy classes for single-axle load and, if required, axle-group load.

[[scls-2-5]]
=== Installation and testing of WIM instruments

For WIM instruments to be used in applications where the individual axle or
axle-group loads are required, the installation and testing requirements specified
in <<annex-b>> and <<annex-a>> respectively, shall be applicable. In particular,
the following effects on the weighing results should be taken into account:

* Lateral forces due to interactions of the control instrument with the vehicle;

* Forces on part of the vehicle by different transient behavior and friction
within the axle suspensions;

* Forces on part of the ramps if there are different levels between the control
instrument and ramp that could lead to varying distribution of the axle load.

Further practical guidance on the installation and operation of these instruments
is provided in <<annex-c>>.

[[scls-2-6]]
=== Agreement between indicating and printing devices

For the same load, there shall be no difference between the weighing results
provided by any two devices having the same scale interval.

[[scls-2-7]]
=== Influence quantities

Refer to <<annex-a>> for test conditions.

==== Temperature

[[scls-2-7-1-1]]
===== Temperature limits

WIM instruments shall comply with the appropriate metrological and technical
requirements at temperatures from stem:[-10 "unitsml(degC)"] to
stem:[+40 "unitsml(degC)"].

However, depending on local environmental conditions, the limits of the temperature
range may differ provided that this range shall not be less than stem:[30 "unitsml(degC)"]
and shall be specified in the descriptive markings.

[[scls-2-7-1-2]]
===== Temperature effect on no-load indication

The indication at zero or near zero shall not vary by more than one scale interval
for a difference in ambient temperature of stem:[5 "unitsml(degC)"].

[[scls-2-7-2]]
==== Power supply

An electronic instrument shall comply with the appropriate metrological and
technical requirements, if the voltage supply varies from the nominal voltage,
stem:[U_"nom"] (if only one voltage is marked on the instrument), or from the
upper and lower limits of the voltage range, stem:[U_"min" - U_"max"], marked
on the instrument at:

* AC mains power:
+
Lower limit is stem:[0.85 xx U_"nom"] or stem:[0.85 xx U_"min"], upper limit
is stem:[1.10 xx U_"nom"] or stem:[1.10 xx U_"max"];

* DC mains power, including rechargeable battery voltage supply if the battery
can be fully (re)charged during the operation of the instrument:
+
Lower limit is the minimum operating voltage, upper limit is stem:[1.20 xx U_"nom"]
or stem:[1.20 xx U_"max"] (for a rechargeable battery, stem:[U_"max"] is the
voltage of a new or fully charged battery of the type specified by the manufacturer);

* Battery power (DC), non-rechargeable batteries, and also including rechargeable
batteries if (re)charging of batteries during the operation of the instrument
is not possible:
+
Lower limit is the minimum operating voltage, upper limit is stem:[U_"nom"]
or stem:[U_"max"];

* stem:[12 "unitsml(V)"] or stem:[24 "unitsml(V)"] road vehicle battery power:
+
Lower limit is stem:[9 "unitsml(V)"] (for a stem:[12 "unitsml(V)"] battery)
or stem:[16 "unitsml(V)"] (for a stem:[24 "unitsml(V)"] battery), upper limit
is stem:[16 "unitsml(V)"] (for a stem:[12 "unitsml(V)"] battery) or stem:[32 "unitsml(V)"]
(for a stem:[24 "unitsml(V)"] battery).

NOTE: The minimum operating voltage is defined as the lowest possible operating
voltage before the instrument is automatically switched off.

Battery-operated and DC mains powered instruments shall either continue to function
correctly or not indicate any mass or load values if the voltage is below the
manufacturer's specified value, the latter being larger than or equal to the
minimum operating voltage.

[[scls-2-8]]
=== Units of measurement

The units of mass and load to be used on an instrument are the kilogram
(stem:["unitsml(kg)"]) or the tonne (stem:["unitsml(t)"]).

[[scls-2-9]]
=== Scale interval for stationary load

If the scale interval for stationary loads is not equal to the scale interval,
stem:[d], it shall not be readily accessible when the instrument is in use for
weighing-in-motion. In addition, if the instrument is not verified for use as
a non-automatic weighing instrument (<<scls-5-1-3>>), the scale interval for
stationary loads shall not be readily accessible and shall only be used for
static testing.

[[scls-2-10]]
=== Operating speed (<<scls-3-5-9>>)

WIM instruments shall comply with the appropriate metrological and technical
requirements at vehicle speeds within the operating speed range:

* given by the operating speed interlock; or

* determined during the weighing test.

Operating speed shall be indicated and/or printed only after the entire vehicle
has been weighed in motion.
