[appendix]
[[annex-a]]
== Performance tests for water meters with electronic devices

[[scls-A-1]]
=== General

This annex defines the programme of performance tests intended to verify that
water meters with electronic devices can perform and function as intended in
a specified environment and under specified conditions. Each test indicates,
where appropriate, the reference conditions for determining the intrinsic error.

These tests supplement any other prescribed test.

When the effect of one influence quantity is being evaluated, all other influence
quantities are to be held relatively constant, at values close to reference
conditions (see <<scls-7-1>> and <<ISO_4064_2_2024,clause=4>>).

[[scls-A-2]]
=== Environmental classification

See <<OIML_D_11_2013>>.

For each performance test, typical test conditions are indicated which correspond
to the climatic and mechanical environmental conditions to which a water meter
is usually exposed.

Water meters with electronic devices are divided into three classes according
to climatic and mechanical environmental conditions:

* class B for fixed meters installed in a building;
* class O for fixed meters installed outdoors;
* class M for mobile meters.

However, the applicant for type approval may indicate specific environmental
conditions in the documentation supplied to the body responsible for type approval,
based on the intended use of the instrument. In this case, the testing laboratory
shall carry out performance tests at severity levels corresponding to these
environmental conditions. If type approval is granted, the data plate shall
indicate the corresponding limits of use. Manufacturers shall inform potential
users of the conditions of use for which a meter is approved.

[[scls-A-3]]
=== Electromagnetic environments

Water meters with electronic devices are divided into two electromagnetic environments:

* E1 -- residential, commercial and light industrial;
* E2 -- industrial.

[[scls-A-4]]
=== Type evaluation and approval of a calculator

[[scls-A-4-1]]
==== {blank}

When an electronic calculator (including indicating device) is submitted for
separate type approval, type evaluation tests shall be conducted on the calculator
(including indicating device) alone, simulating different inputs generated by
appropriate standards (e.g. calibrators).

[[scls-A-4-2]]
==== {blank}

Accuracy tests on the indications of measurement results are required. For this
purpose, the error obtained on the indication of the result is calculated considering
that the true value is the one which takes into account the value of the simulated
quantities applied to inputs of the calculator and using standard methods for
calculation. The MPEs are those given in <<scls-4-2>>.

NOTE: An appropriate MPE for a calculator is 1/10 of the MPE of a complete meter.
However, this is not a requirement. The requirement is given in <<scls-4-2-5>>.

[[scls-A-4-3]]
==== {blank}

The examinations and tests for electronic instruments specified in <<scls-7-2-12>>
shall be performed.

[[scls-A-5]]
=== Performance tests

The tests indicated in <<table-A-1>> involve the electronic part of a water
meter or its devices and may be carried out in any order.

[[table-A-1]]
.Tests involving the electronic part of a water meter or its devices
[cols="^,1,^,^",options="header"]
|===
| ISO 4064-2:2024\|OIML R 49-2:2024, subclause
| Test
| Characteristic under test
| Conditions applied

| 8.2   | Dry heat                                                           | Influence factor | MPE
| 8.3   | Cold                                                               | Influence factor | MPE
| 8.4   | Damp heat, cyclic                                                  | Disturbance      | Significant fault
| 8.5.1 | Mains voltage variation                                            | Influence factor | MPE
| 8.5.1 | Mains frequency variation                                          | Influence factor | MPE
| 8.5.2 | Low voltage of internal battery (not connected to the mains power) | Influence factor | MPE
| 8.6   | Vibration (random)                                                 | Disturbance      | Significant fault
| 8.7   | Mechanical shock                                                   | Disturbance      | Significant fault
| 8.8   | AC mains voltage dips, short interruption voltage variations       | Disturbance      | Significant fault
| 8.9   | Bursts on signal, data and control lines                           | Disturbance      | Significant fault
| 8.10  | Bursts (transients) on AC and DC mains                             | Disturbance      | Significant fault
| 8.11  | Electrostatic discharge                                            | Disturbance      | Significant fault
| 8.12  | Radiated electromagnetic fields                                    | Disturbance      | Significant fault
| 8.13  | Conducted electromagnetic fields                                   | Disturbance      | Significant fault
| 8.14  | Surges on signal, data and control lines                           | Disturbance      | Significant fault
| 8.15  | Surges on AC and DC Mains power lines                              | Disturbance      | Significant fault
| 8.16  | Static magnetic field                                              | Influence factor | MPE
| 8.17  | Absence of flow test                                               | Disturbance      | Significant fault
| 8.18  | Mains power frequency electromagnetic fields test                  | Disturbance      | Significant fault
|===
