== Terms and definitions

The general terms used in this Document are in accordance with the _International Vocabulary of
Metrology -- Basic and General Concepts and Associated Terms_ (VIM), <<V2>>, and
the _International Vocabulary of Terms in Legal Metrology_ (VIML), <<V1>>. Other terms
specific to this Document are defined below.

=== base volume

constant reference volume that corresponds to the displacement of a full stroke of the displacer in the
calibrated section

NOTE: A base volume is usually equivalent to the volume of the calibrated section.

=== calibrated section

specified section in a prover defined with a pipe (or cylinder) and displacer(s) that has a constant crosssectional
area

NOTE: The volume inside a calibrated section, when it has been accurately determined in advance, may
be used to define the base volume of the pipe prover.

=== detector

contact sensor or a non-contact (optical or mechanical) sensor that is used to detect the position of the
displacer

NOTE: A mechanical detector using a cantilever is often employed in certain pipe provers. The lever
is pushed by the displacer and actuates an electrical switch installed outside the pipe wall.
A linear encoder is used for a piston prover to transmit a pulse signal that is proportional to the
displacement of the displacer.

=== displacer

object (usually a sphere or a piston) that travels along with the liquid flowing through the prover and
that is used to define the calibrated section
