[[foreword]]
== Foreword

The International Organization of Legal Metrology (OIML) is a worldwide, intergovernmental organisation whose primary aim is to harmonise the regulations and metrological controls applied by the national metrological services, or related organisations, of its Member States.

The main categories of OIML publications are:

* *International Recommendations (OIML R)*, which are model regulations that establish the metrological characteristics required of certain measuring instruments and which specify methods and equipment for checking their conformity. OIML Member States shall implement these Recommendations to the greatest possible extent;

* *International Documents (OIML D)*, which are informative in nature and which are intended to harmonise and improve work in the field of legal metrology;

* *International Guides (OIML G)*, which are also informative in nature and which are intended to give guidelines for the application of certain requirements to legal metrology; and

* *International Basic Publications (OIML B)*, which define the operating rules of the various OIML structures and systems.

OIML Draft Recommendations, Documents and Guides are developed by Technical Committees or Subcommittees which comprise representatives from the Member States. Certain international and regional institutions also participate on a consultation basis. Cooperative agreements have been established between the OIML and certain institutions, such as ISO and the IEC, with the objective of avoiding contradictory requirements. Consequently, manufacturers and users of measuring instruments, test laboratories, etc. may simultaneously apply OIML publications and those of other institutions.

International Recommendations, Documents, Guides and Basic Publications are published in English (E) and translated into French (F) and are subject to periodic revision.

Additionally, the OIML publishes or participates in the publication of Vocabularies (OIML V) and periodically commissions legal metrology experts to write Expert Reports (OIML E). Expert Reports are intended to provide information and advice, and are written solely from the viewpoint of their author, without the involvement of a Technical Committee or Subcommittee, nor that of the CIML. Thus, they do not necessarily represent the views of the OIML.

This publication -- reference OIML D 30, Edition 2020 (E) -- was developed by Project Group 1 in the OIML Certification System (OIML-CS) Management Committee (OIML-CS/SC 7). It was approved for final publication by the International Committee of Legal Metrology (CIML) by direct CIML online approval in June 2020. It replaces the previous edition dated 2008.

OIML publications may be downloaded from the OIML web site in the form of PDF files. Additional information on OIML publications may be obtained from the Organisation's headquarters:

Bureau International de Métrologie Légale +
11, rue Turgot - 75009 Paris - France +
Telephone: 33 (0)1 48 78 12 82 +
Fax: 33 (0)1 42 82 17 27 +
E-mail: biml@oiml.org +
Internet: www.oiml.org
