[[management-committee]]
== Management Committee (MC)

=== Composition

. the CIML Member of an OIML Member State that has at least one OIML Issuing Authority or Utilizer may designate up to four representatives to participate in the MC. One of the representatives shall be designated by the CIML Member as the "MC Member" for the purposes of voting;

. the Representative of an OIML Corresponding Member that has at least one Associate may designate up to four representatives to participate in the MC;

. a Chairperson, nominated from amongst the representatives from OIML Member States and appointed by the CIML;

. a Deputy Chairperson, nominated from amongst the representatives from OIML Member States and appointed by the CIML;

. an Executive Secretary;

. the TLF Chairperson;

. Secretariats (or their nominated representatives) of relevant OIML TCs/SCs as observers;

. representatives from Organizations in Liaison as observers; and

. representatives from OIML Member States or Corresponding Member Countries that have expressed a clear intention to participate in the OIML-CS, with the agreement of the Chairperson, as observers.

[11.2] The principal duties of the Chairperson are to

. convene and preside over meetings of the MC,

. determine the agenda for MC meetings,

. represent the MC between its meetings, and

. report to the CIML.

=== Meetings and other activities

In addition to its ongoing activities, the MC shall meet at least once a year. At meetings of the MC a delegation of up to three of the representatives from each OIML Member State and Corresponding Member participating in the OIML-CS may attend. For OIML Member States, the MC Member designated by the CIML Member (see 11.1 a) has the vote for that country (see <<voting>>). The Chairperson can invite guests, e.g. guest speakers, to attend MC meetings in support of the activities of the MC.

[[voting]]
=== Voting

==== Eligibility

. the MC Member from each OIML Member State has a vote;

. the Chairperson and Deputy have a vote, if their Member State is not otherwise represented in the MC;

. the representatives from OIML Corresponding Members have a voice but do not have a vote;

. the Executive Secretary does not have a vote;

. the TLF Chairperson does not have a vote;

. secretariats (or their nominated representatives) of OIML TCs/SCs do not have a vote;

. representatives of Organizations in Liaison do not have a vote; and

. representatives from OIML Member States or Corresponding Member Countries that have expressed a clear intention to participate in the OIML-CS do not have a vote.

==== Decisions taken during an MC meeting

Approval, re-approval or suspension of an OIML Issuing Authority or a Test Laboratory requires the support of at least 80 % of the MC Members from OIML Member States. All other proposals require the support of at least half of the MC Members from OIML Member States.

In exceptional cases, an MC Member from an OIML Member State who is unable to be present at an MC meeting may give a proxy either to another representative from their own country, or to another MC Member.

MC members shall not hold more than two proxies (in additional to their own vote) at an MC meeting.

Abstentions are not considered as voting. MC Members who vote against a proposal or abstaining shall provide their reasons for doing so.

==== Decisions taken outside an MC meeting

Decisions are normally taken during meetings. Between meetings, if the Chairperson so decides, voting can take place by correspondence.

Approval, re-approval or suspension of an OIML Issuing Authority or a Test Laboratory requires the support of at least 80 % of the MC Members from OIML Member States. Other decisions shall be valid when two-thirds of the votes cast by MC Members from OIML Member States are in favor.

Abstentions are not considered as votes cast. MC Members who vote against a proposal shall provide their reasons for doing so.

[[duties]]
=== Duties and responsibilities

The MC is responsible for the operation of the OIML-CS under the authority of the CIML. The MC shall

. report annually to the CIML,

. develop and make proposals to the CIML for changes in OIML-CS strategy and policy,

. promote and raise awareness of the OIML-CS and its schemes,

. make proposals to the CIML to extend or reduce the transition period from Scheme B to Scheme A for a measuring instrument category in the OIML-CS,

. make proposals to the CIML on the transition of measuring instrument categories from Scheme A back to Scheme B,

. make decisions on the participation of new OIML Issuing Authorities in a scheme,

. organize periodic reviews on the continuity of participation of OIML Issuing Authorities in a scheme,

. appoint the Review Committee Chairperson and the Test Laboratories Forum Chairperson,

. approve and maintain the list of Legal Metrology Experts and Management System Experts,

. develop recommendations to the CIML for improvements/changes to OIML B 18 Framework for the OIML Certification System (OIML-CS),

. develop, maintain and approve rules and procedures for the operation of the schemes in accordance with OIML B 18 Framework for the OIML Certification System (OIML-CS),

. develop and maintain guidance documents, templates and forms in support of the rules and procedures of OIML B 18 Framework for the OIML Certification System (OIML-CS),

. monitor the operation and effectiveness of the OIML-CS Schemes,

. establish working groups to enhance the efficiency of its operation,

. develop proposals for the content and functionality of the OIML-CS website in relation to the OIML-CS, and

. define the roles and duties of the BIML Secretariat.

=== Review Committee (RC)

The RC is a sub-committee of the MC.

==== Composition

. a minimum of six members from the representatives of OIML Member States in the MC;

. a Chairperson, from amongst the members from OIML Member States, appointed by the MC; and

. the Executive Secretary.

==== The tasks of the RC are to

. review the documentation submitted by potential OIML Issuing Authorities including accreditation certificates and assessment reports, peer assessment reports, etc. and to make recommendations to the MC on the acceptance of potential OIML Issuing Authorities,

. review the documentation submitted by OIML Issuing Authorities for periodic reviews of the participation, and to make recommendations to the MC on the continuation as OIML Issuing Authorities,

. make recommendations to the MC on the validation of the Legal Metrology Experts and Management System Experts who will participate in accreditation or peer assessments of test laboratories, and

. make recommendations to the MC on the validity of complaints.

=== Working Groups

The MC may establish Working Groups (WG), with clearly defined terms of reference, to advise it on matters related to the management of the OIML-CS or to enhance the efficiency of its operation.
