name: generate

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: metanorma/metanorma:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: "Update gems"
        run: |
          bundle update mn2pdf

      - name: Setup Metanorma with oiml flavor
        uses: actions-mn/setup@v3
        with:
          installation-method: gem
          # extra-flavors: oiml
          github-packages-token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

      - name: Install private Fontist fonts
        env:
          GH_TOKEN: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
        run: |
          bundle exec fontist repo setup metanorma "https://${GH_TOKEN}@github.com/metanorma/fontist-formulas-private"
          bundle exec fontist repo update metanorma
          bundle exec fontist install "Futura PT Book"
          bundle exec fontist install "Futura PT Demi"
          bundle exec fontist install "Futura PT Light"

      - name: Metanorma generate site
        uses: actions-mn/build-and-publish@v2
        with:
          agree-to-terms: true
          destination: artifact
          artifact-name: ${{ github.event.repository.name }}-${{ runner.os }}
